function displayMenu (menuNumber: number) {
    if (menuNumber == 1) {
        for (let index = 0; index < 2; index++) {
            veganRecommendation = veganCourses._pickRandom()
            game.splash(veganRecommendation)
            veganCourses.removeAt(veganCourses.indexOf(veganRecommendation))
        }
    } else if (menuNumber == 2) {
        for (let index = 0; index < 2; index++) {
            pescatarianRecommendation = pescatarianCourses._pickRandom()
            game.splash(pescatarianRecommendation)
            pescatarianCourses.removeAt(pescatarianCourses.indexOf(pescatarianRecommendation))
        }
    } else if (menuNumber == 3) {
        for (let index = 0; index < 2; index++) {
            normalRecommendation = normalCourses._pickRandom()
            game.splash(normalRecommendation)
            normalCourses.removeAt(normalCourses.indexOf(normalRecommendation))
        }
    } else {
    	
    }
}
let normalRecommendation = ""
let pescatarianRecommendation = ""
let veganRecommendation = ""
let normalCourses: string[] = []
let pescatarianCourses: string[] = []
let veganCourses: string[] = []
game.showLongText("Hi! Welcome to Viva la Special! We offer inclusive options for those with dietary restrictions!", DialogLayout.Bottom)
let dietaryRestrictions = game.askForNumber("(1) Vegan (2) Pescatarian (3) No restrictions", 3)
let chef = sprites.create(img`
    ..............................
    ........ffffffffffff..........
    ........f1111111111f..........
    ........f1dd1dd1dd1f..........
    ........f1dd1dd1dd1f..........
    ........f1dd1dd1dd1f..........
    ........f1dd1dd1dd1f..........
    ........f1dd1dd1dd1f..........
    ........f1dd1dd1dd1f..........
    ........f1dd1dd1dd1f..........
    ........f1dd1dd1dd1f..........
    ........ffffffffffff..........
    ........feffffefffff..........
    ........fee1feee1fef..........
    ........feeeeeeeeeef..........
    ........feeeeffeeeef..........
    ........ffeeeeeeefff..........
    .........fd111111f............
    ........fd1111111fff..........
    ......ff11111111111ff.........
    .....fee11dd111dd111ff........
    .....fee11d11111d111eef.......
    ......fff1d111111fffeef.......
    .......f11d11111111fff........
    .......f1d11111111df..........
    .......fd1111111111f..........
    .......f111fffff11df..........
    ........fdf.....f1f...........
    ........fff.....fff...........
    ..............................
    `, SpriteKind.Player)
veganCourses = [
"Vegan Chicken Nuggets",
"Tofu Power Bowl",
"Veggie Burger with side of fries",
"Vegan Curry",
"Red leaf"
]
pescatarianCourses = [
"Grilled Swordfish",
"Blackened Salmon",
"Tuna Tartare",
"Nigiri",
"Scallop salad"
]
normalCourses = [
"Mac & Cheese",
"Burger & Fries",
"Chicken Parmesian",
"Turkey Sandwich",
"Steak & Potatoes"
]
displayMenu(dietaryRestrictions)
